# Use the Python 3.9 slim base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /voice_assistant/app

# Copy the Python script and requirements into the container
COPY app /voice_assistant/app

# Create the logs directory within the container
RUN mkdir -p /voice_assistant/logs

# Set the log file path within the container
ENV LOG_FILE_PATH="/voice_assistant/logs/interaction.log"

# Update package lists and install necessary dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libasound2-dev \
    portaudio19-dev \
    libportaudio2 \
    libportaudiocpp0 \
    espeak \
    libespeak1 \
    python3-pyaudio \
    alsa-utils \
    pulseaudio \
    libpulse0 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir -r /voice_assistant/app/requirements.txt

# Set the command to run your application
CMD ["python", "/voice_assistant/app/assistant.py"]
